import { _electron as electron } from 'playwright';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import assert from 'node:assert/strict';

const root = path.resolve(import.meta.dirname, '..');
const executable = process.env.SOCIAL_COPY_QA_EXECUTABLE || path.join(root, 'out/SocialCopyStudio-win32-x64/SocialCopyStudio.exe');
const output = path.join(root, 'output/playwright'); await mkdir(output, { recursive: true });
const dataRoot = path.join(root, 'output/test-data'); await mkdir(dataRoot, { recursive: true });
const work = await mkdtemp(path.join(dataRoot, 'desktop-'));
const ffmpeg = path.join(root, 'resources/media/ffmpeg.exe');
const assertions = [], errors = [];
let application, page, clipboardAvailable = false;
const record = message => { assertions.push(message); console.log('PASS', message); };
const waitFor = async callback => { const start = Date.now(); while (Date.now() - start < 60000) { if (await callback()) return; await new Promise(resolve => setTimeout(resolve, 150)); } throw new Error('Timed out waiting for application condition'); };
const env = { ...process.env, SOCIAL_COPY_DATA_DIRECTORY: path.join(work, 'profile') };
env.PATH = `${process.env.SystemRoot}\\system32;${process.env.SystemRoot}`;
delete env.ELECTRON_RUN_AS_NODE;

async function launch() {
  application = await electron.launch({ executablePath: executable, env, timeout: 30000 });
  page = await application.firstWindow(); page.setDefaultTimeout(15000);
  await application.evaluate(({ BrowserWindow }) => { const window = BrowserWindow.getAllWindows()[0]; window.webContents.setBackgroundThrottling(false); window.hide(); });
  page.on('pageerror', error => errors.push(error.message));
  await page.getByRole('heading', { name: '我的草稿', exact: true }).waitFor();
  clipboardAvailable = await application.evaluate(async ({ clipboard }) => {
    try { await clipboard.writeText('social-copy-clipboard-check'); return await clipboard.readText() === 'social-copy-clipboard-check'; } catch { return false; }
  });
}
async function selectFiles(paths) {
  await application.evaluate(({ dialog }, files) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: files }); }, paths);
}
const photos = () => page.locator('.wechat-proof__photo');
const dismissNotice = async () => { const button = page.getByRole('button', { name: '关闭提示', exact: true }); if (await button.count()) await button.click(); };
const sizeMenuButton = () => page.getByRole('button', { name: '预览尺寸与机型', exact: true });
const openSizeMenu = async () => {
  if (await sizeMenuButton().getAttribute('aria-expanded') !== 'true') await sizeMenuButton().click();
  await page.getByRole('listbox', { name: '预览机型', exact: true }).waitFor();
};
const chooseSize = async label => {
  await openSizeMenu(); const name = label.split(' · ').at(-1);
  for (const option of await page.getByRole('option').all()) if ((await option.innerText()).endsWith(' · ' + name)) { await option.click(); return; }
  throw new Error('Preview preset not found: ' + name);
};

try {
  const images = [];
  for (let i = 0; i < 4; i++) {
    const file = path.join(work, `风景 ${i + 1}.png`);
    const colors = [['#9ebdc5', '#578e92', '#e0d2b6'], ['#bec6a4', '#597458', '#b3ad83'], ['#b9b7ad', '#6f8b90', '#e6c7ad'], ['#c8b9ad', '#8b665c', '#ead8bc']][i];
    execFileSync(ffmpeg, ['-v', 'error', '-f', 'lavfi', '-i', `color=c=${colors[0]}:s=900x1200:d=0.1`, '-vf', `drawbox=x=0:y=550:w=900:h=650:color=${colors[1]}:t=fill,drawbox=x=0:y=920:w=900:h=280:color=${colors[2]}:t=fill,drawbox=x=130:y=250:w=80:h=80:color=#f4e9ca:t=fill`, '-frames:v', '1', '-update', '1', file], { windowsHide: true }); images.push(file);
  }
  const inputVideo = path.join(work, '短视频.mp4');
  execFileSync(ffmpeg, ['-v', 'error', '-f', 'lavfi', '-i', 'testsrc2=size=360x640:rate=30:duration=1.2', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=1.2', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest', inputVideo], { windowsHide: true });

  await launch();
  assert.equal(await page.locator('.library-card').count(), 0);
  assert.equal(await page.getByRole('button', { name: '返回上一层', exact: true }).count(), 0);
  await page.screenshot({ path: path.join(output, '01-library.png') });
  record('Packaged app opens its empty draft library');

  await page.getByRole('button', { name: '新建草稿', exact: true }).click();
  await page.getByRole('region', { name: '预览工作台', exact: true }).waitFor();
  assert.equal(await page.locator('.workbench-editor, .asset-card, .editor-tabs').count(), 0);
  assert.equal(await page.locator('.wechat-proof__add').count(), 1);
  assert.equal(await page.getByRole('textbox', { name: '发布文案', exact: true }).count(), 1);
  await page.screenshot({ path: path.join(output, '02-empty-preview.png') });
  record('Preview contains an image placeholder and inline caption with no left editor');

  assert.equal(await page.getByRole('textbox', { name: '草稿标题', exact: true }).count(), 0);
  const originalDraftId = await page.evaluate(async () => (await window.desktop.listDrafts()).drafts[0].id);
  const originalCard = () => page.locator(`.library-card[data-draft-id="${originalDraftId}"]`);
  const caption = '把时间留给风，把心情留给海。\n\n走走停停，收集一些简单的快乐。🌊\n#周末日常 #慢生活';
  await page.getByRole('textbox', { name: '发布文案', exact: true }).fill(caption);
  assert.equal(await page.getByRole('textbox', { name: '发布文案', exact: true }).inputValue(), caption);
  await waitFor(async () => await page.evaluate(async id => (await window.desktop.listDrafts()).drafts.find(d => d.id === id)?.caption, originalDraftId) === caption);
  await page.screenshot({ path: path.join(output, '03-wechat-caption.png') });
  record('WeChat caption editing updates the preview and saves the complete text');

  const sizeBox = page.locator('.preview-viewport');
  const widthField = page.getByRole('spinbutton', { name: '预览宽度', exact: true });
  const heightField = page.getByRole('spinbutton', { name: '预览高度', exact: true });
  assert.equal(await sizeMenuButton().innerText(), '默认尺寸');
  assert.equal(await widthField.count(), 1);
  await openSizeMenu();
  assert.match(await page.getByRole('option').first().innerText(), /^520 × \d+ · 默认尺寸$/);
  await page.keyboard.press('Escape');
  assert.equal(await sizeMenuButton().getAttribute('aria-expanded'), 'false');
  await sizeMenuButton().focus(); await page.keyboard.press('ArrowDown');
  await page.keyboard.press('ArrowDown'); await page.keyboard.press('Enter');
  assert.equal(await sizeMenuButton().innerText(), 'iPhone SE');
  const longCaption = caption + '\n' + '窄屏排版也要保留完整文案与表情。👨‍👩‍👧‍👦 '.repeat(25);
  await page.getByRole('textbox', { name: '发布文案', exact: true }).fill(longCaption);
  await waitFor(async () => await page.evaluate(async id => (await window.desktop.listDrafts()).drafts.find(d => d.id === id)?.caption, originalDraftId) === longCaption);
  const originalSnapshot = await page.evaluate(async id => (await window.desktop.listDrafts()).drafts.find(d => d.id === id), originalDraftId);
  await chooseSize('375 × 667 · iPhone SE');
  await openSizeMenu();
  await waitFor(async () => await widthField.inputValue() === '375' && await heightField.inputValue() === '667');
  const presetRect = await sizeBox.boundingBox();
  assert.equal(presetRect.width, 375); assert.equal(presetRect.height, 667);
  await widthField.fill('460'); await widthField.press('Enter');
  await heightField.fill('500'); await heightField.press('Enter');
  assert.equal(await sizeMenuButton().innerText(), '自定义');
  assert.equal(await page.getByRole('option', { name: '460 × 500 · 自定义', exact: true }).getAttribute('aria-selected'), 'true');
  await widthField.fill(''); await widthField.press('Tab');
  assert.equal(await widthField.inputValue(), '460');
  await widthField.fill('10'); await widthField.press('Enter');
  assert.equal(await widthField.inputValue(), '240');
  await waitFor(async () => await page.getByRole('textbox', { name: '发布文案', exact: true }).evaluate(field => field.clientHeight >= field.scrollHeight - 1));
  assert.equal(await page.getByRole('textbox', { name: '发布文案', exact: true }).inputValue(), longCaption);
  await widthField.fill('400'); await widthField.press('Enter');
  await sizeBox.scrollIntoViewIfNeeded();
  await waitFor(async () => { const rect = await sizeBox.boundingBox(); return rect.width === 400 && rect.height === 500; });
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  const resizeStart = await sizeBox.boundingBox();
  await page.mouse.move(resizeStart.x + resizeStart.width - 3, resizeStart.y + resizeStart.height - 3);
  await page.mouse.down();
  await page.mouse.move(resizeStart.x + resizeStart.width + 37, resizeStart.y + resizeStart.height + 57, { steps: 12 });
  await page.mouse.up();
  await openSizeMenu();
  await waitFor(async () => Number(await widthField.inputValue()) > 420 && Number(await heightField.inputValue()) > 540);
  assert.deepEqual(await page.evaluate(async id => (await window.desktop.listDrafts()).drafts.find(d => d.id === id), originalDraftId), originalSnapshot);
  await page.screenshot({ path: path.join(output, '15-custom-preview-size.png') });
  await chooseSize('520 × 780 · 默认尺寸');
  assert.equal(await sizeMenuButton().innerText(), '默认尺寸');
  await page.getByRole('textbox', { name: '发布文案', exact: true }).fill(caption);
  await waitFor(async () => await page.evaluate(async id => (await window.desktop.listDrafts()).drafts.find(d => d.id === id)?.caption, originalDraftId) === caption);
  const maxWidth = Number(await widthField.getAttribute('max')), maxHeight = Number(await heightField.getAttribute('max'));
  await widthField.fill('99999'); await widthField.press('Enter');
  await heightField.fill('99999'); await heightField.press('Enter');
  assert.equal(Number(await widthField.inputValue()), maxWidth); assert.equal(Number(await heightField.inputValue()), maxHeight);
  await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1080, 720));
  await waitFor(async () => await page.evaluate(() => {
    const outer = document.querySelector('.workbench-preview-scroll').getBoundingClientRect(), inner = document.querySelector('.preview-viewport').getBoundingClientRect();
    return window.innerWidth <= 1080 && inner.left >= outer.left && inner.right <= outer.right && inner.top >= outer.top && inner.bottom <= outer.bottom;
  }));
  const constrained = await page.evaluate(() => {
    const host = document.querySelector('.workbench-preview-scroll'), box = document.querySelector('.preview-viewport');
    const outer = host.getBoundingClientRect(), inner = box.getBoundingClientRect();
    return inner.left >= outer.left && inner.right <= outer.right && inner.top >= outer.top && inner.bottom <= outer.bottom;
  });
  assert.equal(constrained, true);
  await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1440, 930));
  await chooseSize('默认尺寸');
  record('Combined header edits dimensions, applies presets and limits both input and resize to the available workspace');

  await page.getByRole('navigation', { name: '工作区导航' }).getByRole('button', { name: '素材库', exact: true }).click();
  await page.getByRole('heading', { name: '素材库', exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: '素材库', exact: true }).count(), 0);
  assert.equal(await page.locator('.library-storage-path').innerText(), '图片保存位置：' + path.join(work, 'profile', 'library', 'assets'));
  await page.getByRole('button', { name: '返回上一层', exact: true }).click();
  await page.getByRole('region', { name: '预览工作台', exact: true }).waitFor();
  assert.equal(await page.getByRole('textbox', { name: '发布文案', exact: true }).inputValue(), caption);
  await page.locator('.wechat-proof__add').click();
  const firstPicker = page.getByRole('dialog', { name: '添加图片', exact: true });
  await firstPicker.getByRole('button', { name: '返回上一层', exact: true }).click();
  await firstPicker.waitFor({ state: 'hidden' });
  assert.equal(await page.locator('.wechat-proof').count(), 1);
  record('Home has no back button; library returns to the originating draft and picker back returns to its parent');

  await selectFiles(images.slice(0, 3));
  await page.locator('.wechat-proof__add').click();
  await page.getByRole('dialog', { name: '添加图片', exact: true }).getByRole('button', { name: '从电脑导入图片', exact: true }).click();
  await waitFor(async () => await photos().count() === 3);
  await page.getByRole('dialog', { name: '添加图片', exact: true }).waitFor({ state: 'hidden' });
  await waitFor(async () => await photos().first().isEnabled());
  assert.equal(await page.locator('.wechat-proof__add').count(), 1);
  assert.equal(await page.locator('.preview-remove').count(), 0);
  assert.equal(await photos().first().getAttribute('draggable'), 'false');
  const readonlyOrder = await photos().locator('img').evaluateAll(images => images.map(image => image.src));
  await photos().nth(2).focus();
  await page.keyboard.press('Alt+ArrowLeft');
  assert.deepEqual(await photos().locator('img').evaluateAll(images => images.map(image => image.src)), readonlyOrder);
  await page.getByRole('button', { name: '编辑模式', exact: true }).click();
  assert.equal(await page.locator('.preview-remove').count(), 3);
  const first = await photos().first().locator('img').getAttribute('src');
  await photos().first().dragTo(photos().nth(2));
  await waitFor(async () => await photos().nth(2).locator('img').getAttribute('src') === first);
  await photos().nth(2).focus();
  await page.keyboard.press('Alt+ArrowLeft');
  await waitFor(async () => await photos().nth(1).locator('img').getAttribute('src') === first);
  await photos().first().click();
  await page.getByRole('dialog', { name: '调整画面' }).waitFor();
  assert.equal(await page.getByRole('dialog', { name: '调整画面' }).getByRole('button', { name: /^(取消|移除图片|关闭)$/ }).count(), 0);
  await page.getByRole('button', { name: '1:1', exact: true }).click();
  await page.screenshot({ path: path.join(output, '04-image-editor.png') });
  await page.getByRole('button', { name: '应用调整', exact: true }).click();
  await page.getByRole('dialog', { name: '调整画面' }).waitFor({ state: 'hidden' });
  await page.screenshot({ path: path.join(output, '05-wechat-preview.png') });
  await page.getByRole('button', { name: '完成编辑', exact: true }).click();
  assert.equal(await page.locator('.preview-remove').count(), 0);
  assert.equal(await photos().first().getAttribute('draggable'), 'false');
  record('WeChat removal and sorting require edit mode; crop dialog retains only back and apply actions');

  await page.getByRole('switch', { name: '抖音预览', exact: true }).click();
  assert.equal(await page.locator('.douyin-proof').count(), 1);
  assert.equal(await page.locator('.douyin-proof__add').count(), 1);
  await page.getByRole('button', { name: '编辑发布文案', exact: true }).click();
  const douyinCaption = caption + '\n#新话题';
  await page.getByRole('textbox', { name: '发布文案', exact: true }).fill(douyinCaption);
  assert.equal(await page.locator('.douyin-proof__hashtag').count(), 0);
  await page.locator('.douyin-proof__header').click();
  assert.equal(await page.locator('.douyin-proof__hashtag').count(), 3);
  assert.equal(await page.locator('.layout-caption').innerText(), douyinCaption);
  await selectFiles([images[3]]);
  await page.locator('.douyin-proof__add').click();
  await page.getByRole('dialog', { name: '添加图片', exact: true }).getByRole('button', { name: '从电脑导入图片', exact: true }).click();
  await waitFor(async () => await page.locator('.image-counter').innerText() === '1/4');
  await page.getByRole('button', { name: '下一张', exact: true }).click();
  const movingImage = await page.locator('.douyin-proof__image img').getAttribute('src');
  await page.getByRole('button', { name: '编辑模式', exact: true }).click();
  const bar = await page.locator('.douyin-proof__segments').boundingBox();
  await page.locator('.douyin-proof__image').dragTo(page.locator('.douyin-proof__segments'), { targetPosition: { x: bar.width * .86, y: bar.height / 2 } });
  assert.equal(await page.locator('.image-counter').innerText(), '4/4');
  assert.equal(await page.locator('.douyin-proof__image img').getAttribute('src'), movingImage);
  await page.locator('.douyin-proof__image').click();
  await page.getByRole('dialog', { name: '调整画面' }).waitFor();
  await page.getByRole('dialog', { name: '调整画面' }).getByRole('button', { name: '返回上一层', exact: true }).click();
  await page.screenshot({ path: path.join(output, '06-douyin-preview.png') });
  await page.getByRole('button', { name: '完成编辑', exact: true }).click();
  assert.equal(await page.locator('.preview-remove').count(), 0);
  assert.equal(await page.locator('.douyin-proof__image').getAttribute('draggable'), 'false');
  await page.locator('.douyin-proof__media').focus();
  await page.keyboard.press('Alt+ArrowLeft');
  assert.equal(await page.locator('.image-counter').innerText(), '4/4');
  assert.equal(await page.locator('.douyin-proof__image img').getAttribute('src'), movingImage);
  await page.keyboard.press('ArrowLeft');
  assert.equal(await page.locator('.image-counter').innerText(), '3/4');
  await page.getByRole('button', { name: '下一张', exact: true }).click();
  record('Douyin placeholder adds a fourth image and inline caption editing updates topics');

  await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1080, 720));
  await waitFor(async () => await page.evaluate(() => window.innerWidth <= 1080));
  const viewport = await page.evaluate(() => {
    const button = [...document.querySelectorAll('.workbench-toolbar button')].find(item => item.textContent.includes('导出素材包'));
    const rect = button.getBoundingClientRect(); const target = document.elementFromPoint(rect.left + rect.width / 2, rect.top + rect.height / 2);
    return { fits: document.documentElement.scrollWidth <= window.innerWidth, exportVisible: rect.left >= 0 && rect.right <= window.innerWidth && rect.bottom <= window.innerHeight, exportUnobstructed: button.contains(target) };
  });
  assert.deepEqual(viewport, { fits: true, exportVisible: true, exportUnobstructed: true });
  await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1440, 930));
  record('Preview controls and export remain accessible in the minimum desktop window');

  await page.getByRole('button', { name: '编辑模式', exact: true }).click();
  await page.getByRole('button', { name: '另存草稿', exact: true }).click();
  await page.getByText('已另存为新草稿，原草稿保留', { exact: true }).waitFor();
  const copies = await page.evaluate(() => window.desktop.listDrafts());
  assert.equal(copies.drafts.length, 2);
  assert.ok(copies.drafts.every(d => d.caption === douyinCaption && !('title' in d)));
  assert.equal(await page.locator('.preview-remove').count(), 0);
  await dismissNotice();
  await page.getByRole('button', { name: '编辑发布文案', exact: true }).click();
  await page.getByRole('textbox', { name: '发布文案', exact: true }).fill('副本文案：' + douyinCaption);
  await page.locator('.douyin-proof__header').click();
  await page.getByRole('button', { name: '编辑模式', exact: true }).click();
  await page.getByRole('switch', { name: '抖音预览', exact: true }).click();
  const removedId = (await photos().last().locator('img').getAttribute('src')).split('/')[3];
  await page.getByRole('button', { name: '移除第 4 张图片', exact: true }).click();
  await waitFor(async () => await photos().count() === 3);
  assert.equal(await page.getByRole('dialog', { name: '调整画面' }).count(), 0);
  assert.equal(await page.evaluate(async id => (await window.desktop.getAsset(id)).id, removedId), removedId);
  await page.getByRole('switch', { name: '抖音预览', exact: true }).click();
  await page.locator('.douyin-proof__image-wrap .preview-remove').click();
  await waitFor(async () => (await page.locator('.image-counter').innerText()).endsWith('/2'));
  assert.equal(await page.getByRole('dialog', { name: '调整画面' }).count(), 0);
  await page.locator('.douyin-proof__image-wrap .preview-remove').click();
  await waitFor(async () => await page.locator('.image-counter').innerText() === '1/1');
  await page.locator('.douyin-proof__image-wrap .preview-remove').click();
  await page.locator('.douyin-proof__add-empty').waitFor();
  assert.equal(await page.locator('.preview-remove').count(), 0);
  record('Both preview delete buttons remove only the selected draft item; save-as starts outside edit mode');
  await page.getByRole('button', { name: '返回上一层', exact: true }).click();
  await page.getByRole('heading', { name: '我的草稿', exact: true }).waitFor();
  assert.equal(await page.locator('.library-card').count(), 2);
  assert.equal(await originalCard().locator('.draft-caption-name').innerText(), douyinCaption.replace(/\s+/g, ' ').trim());
  await page.getByRole('textbox', { name: '搜索草稿', exact: true }).fill('没有这个标题');
  assert.equal(await page.locator('.library-card').count(), 0);
  await page.getByRole('button', { name: '清空搜索', exact: true }).click();
  await page.getByRole('combobox', { name: '添加平台标签', exact: true }).selectOption('moments');
  assert.equal(await page.locator('.library-card').count(), 0);
  await page.getByRole('combobox', { name: '添加平台标签', exact: true }).selectOption('douyin');
  assert.equal(await page.locator('.library-card').count(), 2);
  await page.getByRole('textbox', { name: '搜索草稿', exact: true }).fill('副本');
  assert.equal(await page.locator('.library-card').count(), 1);
  await page.getByRole('button', { name: '移除抖音标签', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: '搜索草稿', exact: true }).inputValue(), '副本');
  assert.equal(await page.locator('.library-card').count(), 1);
  await page.getByRole('button', { name: '清空搜索', exact: true }).click();
  await page.getByRole('combobox', { name: '添加平台标签', exact: true }).selectOption('douyin');
  await page.getByRole('textbox', { name: '搜索草稿', exact: true }).fill('时间 慢生活');
  assert.equal(await page.locator('.library-card').count(), 2);
  await page.screenshot({ path: path.join(output, '12-tag-search.png') });
  await page.getByRole('button', { name: '清空搜索', exact: true }).click();
  await originalCard().locator('.library-card-open').click();
  await page.getByRole('button', { name: '返回上一层', exact: true }).click();
  await page.locator('.library-card').filter({ hasText: '副本' }).getByRole('button', { name: /^删除草稿 / }).click();
  await page.getByRole('dialog', { name: '删除这份草稿？' }).getByRole('button', { name: '删除草稿', exact: true }).click();
  await page.getByRole('dialog', { name: '删除这份草稿？' }).waitFor({ state: 'hidden' });
  await page.getByRole('heading', { name: '我的草稿', exact: true }).waitFor();
  assert.equal(await page.locator('.library-card').count(), 1);
  await originalCard().locator('.library-card-open').click();
  record('Caption supplies the draft name; save-as preserves text without naming; search and deletion keep the original intact');

  await page.getByRole('navigation', { name: '工作区导航' }).getByRole('button', { name: '素材库', exact: true }).click();
  await page.getByRole('button', { name: '从视频取材', exact: true }).click();
  await selectFiles([inputVideo]);
  await page.locator('.video-source-label').getByRole('button', { name: '选择视频', exact: true }).click();
  await waitFor(async () => await page.locator('.video-source-label').innerText().then(t => t.includes('短视频.mp4')));
  await page.getByRole('button', { name: '下一帧', exact: true }).click();
  await page.getByRole('button', { name: '截取并保存到素材库', exact: true }).click();
  await page.getByText('素材已保存到素材库', { exact: true }).waitFor();
  await dismissNotice();
  await page.getByRole('button', { name: '制作实况', exact: true }).click();
  await page.getByRole('checkbox', { name: '保留原声', exact: true }).uncheck();
  await page.getByRole('button', { name: '制作并保存到素材库', exact: true }).click();
  await page.getByText('素材已保存到素材库', { exact: true }).waitFor();
  await page.getByRole('dialog', { name: '视频取材', exact: true }).getByRole('button', { name: '返回上一层', exact: true }).click();
  await dismissNotice();
  assert.equal(await page.evaluate(async id => (await window.desktop.listDrafts()).drafts.find(d => d.id === id).items.length, originalDraftId), 4);
  await page.getByRole('checkbox', { name: /^选择 短视频\.mp4 · .*秒$/ }).check();
  await page.getByRole('checkbox', { name: '选择 短视频.mp4 · 实况', exact: true }).check();
  const beforeNewDraft = await page.evaluate(() => window.desktop.listDrafts());
  await page.getByRole('button', { name: '加入到新草稿', exact: true }).click();
  await page.getByRole('region', { name: '预览工作台', exact: true }).waitFor();
  assert.equal(await photos().count(), 2);
  const afterNewDraft = await page.evaluate(() => window.desktop.listDrafts());
  assert.equal(afterNewDraft.drafts.length, beforeNewDraft.drafts.length + 1);
  assert.deepEqual(afterNewDraft.drafts.find(d => d.id === originalDraftId), beforeNewDraft.drafts.find(d => d.id === originalDraftId));
  await dismissNotice();
  await page.getByRole('button', { name: '返回上一层', exact: true }).click();
  await originalCard().locator('.library-card-open').click();
  await page.locator('.douyin-proof__add').click();
  const videoPicker = page.getByRole('dialog', { name: '添加图片', exact: true });
  await videoPicker.getByRole('checkbox', { name: /^选择 短视频\.mp4 · .*秒$/ }).check();
  await videoPicker.getByRole('checkbox', { name: '选择 短视频.mp4 · 实况', exact: true }).check();
  await videoPicker.getByRole('button', { name: '加入当前草稿', exact: true }).click();
  await waitFor(async () => (await page.locator('.image-counter').innerText()).endsWith('/6'));
  await page.getByRole('switch', { name: '抖音预览', exact: true }).click();
  assert.equal(await photos().count(), 6);
  await page.locator('.wechat-proof__live').click();
  await page.getByRole('dialog', { name: '实况预览' }).waitFor();
  await page.getByRole('dialog').getByRole('button', { name: '返回上一层', exact: true }).click();
  record('Library selection creates an independent draft; preview picker appends video materials to the existing draft');

  await page.getByRole('button', { name: '导出素材包', exact: true }).click();
  const exportParent = path.join(work, 'exports'); await mkdir(exportParent);
  await selectFiles([exportParent]);
  await page.getByRole('button', { name: '选择位置', exact: true }).click();
  await page.getByRole('button', { name: '开始导出', exact: true }).click();
  await page.getByRole('heading', { name: '素材包已保存', exact: true }).waitFor();
  const folder = await page.locator('.export-success .destination-path').innerText();
  assert.equal(await readFile(path.join(folder, '文案.txt'), 'utf8'), douyinCaption);
  const manifest = JSON.parse(await readFile(path.join(folder, '素材清单.json'), 'utf8'));
  assert.equal(manifest.items.length, 6); assert.equal(manifest.items[5].files.length, 3);
  assert.equal(manifest.deviceVerification, 'pending');
  await page.screenshot({ path: path.join(output, '07-export.png') });
  record('Preview toolbar exports ordered images, Live Photo formats and inline caption');

  await page.getByRole('dialog', { name: '导出完成', exact: true }).getByRole('button', { name: '返回上一层', exact: true }).click();
  await page.getByRole('button', { name: '导出素材包', exact: true }).click();
  await page.getByRole('button', { name: /ZIP 压缩包/ }).click();
  await page.getByRole('button', { name: '开始导出', exact: true }).click();
  await page.getByRole('heading', { name: '素材包已保存', exact: true }).waitFor();
  const zip = await page.locator('.export-success .destination-path').innerText();
  assert.equal((await readFile(zip)).subarray(0, 2).toString(), 'PK');
  await page.getByRole('dialog').getByRole('button', { name: '返回上一层', exact: true }).click();
  record('ZIP export remains available from the preview toolbar');

  await page.getByRole('textbox', { name: '发布文案', exact: true }).fill(douyinCaption + '\n刚刚补上的一句。');
  await chooseSize('412 × 915 · Pixel 7');
  await application.close(); application = null;
  await launch();
  await originalCard().locator('.library-card-open').click();
  assert.equal(await page.getByRole('textbox', { name: '发布文案', exact: true }).inputValue(), douyinCaption + '\n刚刚补上的一句。');
  assert.equal(await photos().count(), 6);
  assert.equal(await sizeMenuButton().innerText(), 'Pixel 7');
  await openSizeMenu();
  assert.equal(await page.getByRole('spinbutton', { name: '预览宽度', exact: true }).inputValue(), '412');
  assert.equal(Number(await page.getByRole('spinbutton', { name: '预览高度', exact: true }).inputValue()), Math.min(915, Number(await page.getByRole('spinbutton', { name: '预览高度', exact: true }).getAttribute('max'))));
  await chooseSize('520 × 780 · 默认尺寸');
  record('Preview device and dimensions survive application restart');
  record('Closing while editing inline caption flushes the draft for restart');

  await page.getByRole('button', { name: '返回上一层', exact: true }).click();
  await page.getByRole('button', { name: '新建草稿', exact: true }).click();
  await page.getByRole('switch', { name: '抖音预览', exact: true }).click();
  await page.locator('.douyin-proof__add-empty').waitFor();
  await page.getByRole('button', { name: '编辑发布文案', exact: true }).click();
  await page.getByRole('textbox', { name: '发布文案', exact: true }).fill('只有文字也能保存。');
  await page.getByRole('button', { name: '导出素材包', exact: true }).click();
  await selectFiles([exportParent]);
  await page.getByRole('button', { name: '选择位置', exact: true }).click();
  await page.getByRole('button', { name: '开始导出', exact: true }).click();
  await page.getByRole('heading', { name: '素材包已保存', exact: true }).waitFor();
  const textOnlyFolder = await page.locator('.export-success .destination-path').innerText();
  assert.equal(await readFile(path.join(textOnlyFolder, '文案.txt'), 'utf8'), '只有文字也能保存。');
  assert.equal(JSON.parse(await readFile(path.join(textOnlyFolder, '素材清单.json'), 'utf8')).items.length, 0);
  record('Text-only Douyin draft can be edited and exported directly in preview');

  await page.getByRole('dialog').getByRole('button', { name: '返回上一层', exact: true }).click();
  await dismissNotice();
  await page.getByRole('navigation', { name: '工作区导航' }).getByRole('button', { name: '素材库', exact: true }).click();
  await page.getByRole('heading', { name: '素材库', exact: true }).waitFor();
  await waitFor(async () => await page.locator('.material-card').count() >= 7);
  await page.getByRole('combobox', { name: '素材分类', exact: true }).selectOption('video');
  await page.getByRole('button', { name: '打开视频取材', exact: true }).click();
  await page.locator('.video-source-label').filter({ hasText: '短视频.mp4' }).waitFor();
  await page.getByRole('button', { name: '截取并保存到素材库', exact: true }).click();
  await page.getByText('素材已保存到素材库', { exact: true }).waitFor();
  await page.getByRole('dialog', { name: '视频取材', exact: true }).getByRole('button', { name: '返回上一层', exact: true }).click();
  await dismissNotice();
  record('Global library includes existing images, Live Photos and reusable imported videos');

  await page.getByRole('combobox', { name: '素材分类', exact: true }).selectOption('all');
  await selectFiles([path.join(root, 'public/ai-examples/product-before.png')]);
  await page.getByRole('button', { name: '从电脑导入图片', exact: true }).click();
  await page.getByRole('searchbox', { name: '搜索素材', exact: true }).fill('product-before');
  await page.getByRole('button', { name: '查看素材 product-before.png', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: '素材名称', exact: true }).count(), 0);
  await page.getByRole('button', { name: '编辑素材名称', exact: true }).click();
  await page.getByRole('textbox', { name: '素材名称', exact: true }).fill('取消这次改名');
  await page.getByRole('button', { name: '取消', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: '素材名称', exact: true }).count(), 0);
  await page.getByRole('button', { name: '编辑素材名称', exact: true }).click();
  await page.getByRole('textbox', { name: '素材名称', exact: true }).fill('案例原图');
  await page.getByRole('button', { name: '应用', exact: true }).click();
  await page.getByRole('searchbox', { name: '搜索素材', exact: true }).fill('案例原图');
  await page.locator('.material-card').getByRole('button', { name: '收藏', exact: true }).click();
  await waitFor(async () => await page.locator('.favorite-button svg').getAttribute('fill') === 'currentColor');
  assert.equal(await page.getByRole('option', { name: '已归档', exact: true }).count(), 0);
  await page.getByRole('combobox', { name: '素材分类', exact: true }).selectOption('favorites');
  assert.equal(await page.locator('.material-card').count(), 1);
  await page.getByRole('button', { name: '查看素材 案例原图', exact: true }).click();
  assert.equal(await page.getByRole('region', { name: '素材详情', exact: true }).count(), 0);
  await dismissNotice();
  await page.screenshot({ path: path.join(output, '08-global-library.png') });
  record('Global material import, rename apply/cancel, star favorite and repeated-click detail collapse work');

  await page.getByRole('combobox', { name: '素材分类', exact: true }).selectOption('all');
  await selectFiles([path.join(root, 'public/ai-examples/food-before.png'), path.join(root, 'public/ai-examples/food-after.png')]);
  await page.getByRole('button', { name: '从电脑导入图片', exact: true }).click();
  await page.getByRole('searchbox', { name: '搜索素材', exact: true }).fill('food-');
  await page.getByRole('checkbox', { name: '选择 food-before.png', exact: true }).check();
  await page.getByRole('checkbox', { name: '选择 food-after.png', exact: true }).check();
  await page.getByRole('button', { name: '批量删除', exact: true }).click();
  await page.getByRole('dialog', { name: '删除所选素材？', exact: true }).getByRole('button', { name: '返回上一层', exact: true }).click();
  assert.equal(await page.locator('.material-card').count(), 2);
  await application.evaluate(({ shell }, destination) => {
    shell.trashItem = async directory => { await process.getBuiltinModule('node:fs').promises.rename(directory, destination); };
  }, path.join(work, 'recycled-batch'));
  await page.getByRole('button', { name: '批量删除', exact: true }).click();
  await page.getByRole('button', { name: '移到回收站', exact: true }).click();
  await page.getByText('已将 2 项素材移到回收站', { exact: true }).waitFor();
  await waitFor(async () => await page.locator('.material-card').count() === 0);
  await dismissNotice();
  record('Batch delete confirmation can return; selected images are removed together (recycle boundary redirected to retained fixtures)');
  await page.getByRole('searchbox', { name: '搜索素材', exact: true }).fill('案例原图');

  await page.getByRole('button', { name: '查看素材 案例原图', exact: true }).click();
  await page.getByRole('region', { name: '素材详情', exact: true }).getByRole('button', { name: 'AI 图片优化', exact: true }).click();
  await page.getByRole('heading', { name: '选择一种优化方向', exact: true }).waitFor();
  assert.equal(await page.locator('.template-option').count(), 20);
  await page.getByRole('button', { name: '商品柔光 商品 · 让材质、轮廓和背景更干净。', exact: true }).click();
  await page.getByRole('button', { name: '复制原图', exact: true }).click();
  if (clipboardAvailable) {
    await page.getByText('图片已复制，请先粘贴到外部工具，再复制提示词', { exact: true }).waitFor();
    const clipboardImage = await application.evaluate(async ({ clipboard, nativeImage }) => {
      const items = await clipboard.read(); const item = items.find(value => value.types.includes('image/png'));
      if (!item) return null; const blob = await item.getType('image/png');
      return nativeImage.createFromBuffer(Buffer.from(await blob.arrayBuffer())).getSize();
    });
    assert.ok(clipboardImage?.width > 1000 && clipboardImage.height > 1000);
  } else await page.getByRole('alert').filter({ hasText: '系统剪贴板暂不可用' }).waitFor();
  await dismissNotice();
  const prompt = await page.getByRole('textbox', { name: '优化提示词', exact: true }).inputValue();
  await page.getByRole('textbox', { name: '优化提示词', exact: true }).fill(prompt + '\n自定义：保留完整杯柄。');
  await page.getByRole('button', { name: '复制提示词', exact: true }).click();
  if (clipboardAvailable) {
    await page.getByText('提示词已复制', { exact: true }).waitFor();
    assert.equal(await application.evaluate(({ clipboard }) => clipboard.readText()), prompt + '\n自定义：保留完整杯柄。');
  } else await page.getByRole('alert').filter({ hasText: '系统剪贴板暂不可用' }).waitFor();
  await dismissNotice();
  await page.screenshot({ path: path.join(output, '09-ai-copy-workflow.png') });
  record(clipboardAvailable ? '20 editable templates; image and prompt copied to OS clipboard' : '20 editable templates; image and prompt copy report inaccessible clipboard with retry');

  await page.getByRole('button', { name: '前后对比案例', exact: true }).click();
  await waitFor(async () => await page.locator('.optimization-example img').evaluateAll(imgs => imgs.length === 4 && imgs.every(img => img.complete && img.naturalWidth > 0)));
  await page.screenshot({ path: path.join(output, '10-ai-examples.png') });
  await page.locator('.optimization-example').first().getByRole('button', { name: '滑动对比', exact: true }).click();
  const range = page.getByRole('slider', { name: '商品案例对比位置', exact: true });
  await range.fill('25'); assert.equal(await range.inputValue(), '25');
  await range.focus(); await page.keyboard.press('ArrowRight'); assert.equal(await range.inputValue(), '26');
  await page.getByRole('button', { name: '优化图片', exact: true }).click();
  await selectFiles([path.join(root, 'public/ai-examples/product-after.png')]);
  await page.getByRole('button', { name: '导入优化结果', exact: true }).click();
  await page.getByRole('button', { name: '复制优化图', exact: true }).waitFor();
  await dismissNotice();
  await page.locator('.optimization-result').scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(output, '11-ai-result.png') });
  await page.getByRole('button', { name: '将结果加入当前草稿', exact: true }).click();
  await page.getByRole('region', { name: '预览工作台', exact: true }).waitFor();
  assert.equal(await page.locator('.image-counter').innerText(), '1/1');
  const manualResult = (await page.evaluate(() => window.desktop.listLibrary())).assets.find(a => a.optimization);
  assert.equal(manualResult.optimization.prompt, prompt + '\n自定义：保留完整杯柄。');
  record('Bundled examples render offline and manual results preserve provenance, compare and enter a draft');

  await dismissNotice();
  await page.locator('.douyin-proof__add').click();
  const picker = page.getByRole('dialog', { name: '添加图片', exact: true });
  await picker.getByRole('searchbox', { name: '搜索素材', exact: true }).fill('案例原图');
  await picker.getByRole('checkbox', { name: '选择 案例原图', exact: true }).check();
  await picker.getByRole('button', { name: '加入当前草稿', exact: true }).click();
  assert.equal(await page.locator('.image-counter').innerText(), '1/2');
  await dismissNotice();
  await page.locator('.douyin-proof__add').click();
  await picker.getByRole('searchbox', { name: '搜索素材', exact: true }).fill('案例原图');
  assert.equal(await picker.getByRole('checkbox', { name: '选择 案例原图', exact: true }).isDisabled(), true);
  await picker.getByRole('button', { name: '返回上一层', exact: true }).click();
  await application.close(); application = null;
  await launch();
  await page.getByRole('navigation', { name: '工作区导航' }).getByRole('button', { name: '素材库', exact: true }).click();
  await page.getByRole('combobox', { name: '素材分类', exact: true }).selectOption('ai');
  await page.getByRole('button', { name: '查看素材 product-after.png', exact: true }).click();
  await page.getByRole('region', { name: '素材详情', exact: true }).getByRole('button', { name: 'AI 图片优化', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: '优化提示词', exact: true }).inputValue(), prompt + '\n自定义：保留完整杯柄。');
  assert.equal(await page.locator('.optimization-result img').count(), 2);
  record('Preview + reuses library assets without duplicates; comparison and prompt survive restart');

  await page.getByRole('button', { name: '返回上一层', exact: true }).click();
  await page.getByRole('heading', { name: '素材库', exact: true }).waitFor();
  await page.getByRole('button', { name: '返回上一层', exact: true }).click();
  await page.getByRole('heading', { name: '我的草稿', exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: '返回上一层', exact: true }).count(), 0);
  record('AI returns to its library parent and then home without a back loop');
  while (await page.locator('.library-card').count() < 10) {
    await page.getByRole('button', { name: '新建草稿', exact: true }).click();
    await page.getByRole('region', { name: '预览工作台', exact: true }).waitFor();
    await page.getByRole('button', { name: '返回上一层', exact: true }).click();
    await page.getByRole('heading', { name: '我的草稿', exact: true }).waitFor();
  }
  assert.equal(await page.getByRole('button', { name: '新建草稿', exact: true }).isDisabled(), true);
  await page.getByRole('textbox', { name: '搜索草稿', exact: true }).fill('不匹配的筛选');
  assert.equal(await page.locator('.library-card').count(), 0);
  assert.equal(await page.getByRole('button', { name: '新建草稿', exact: true }).isDisabled(), true);
  await page.getByRole('button', { name: '清空搜索', exact: true }).click();
  const capacity = await page.evaluate(async () => {
    const { drafts } = await window.desktop.listDrafts();
    const results = await Promise.allSettled([window.desktop.createDraft('moments'), window.desktop.saveDraftAs(drafts[0].id)]);
    return { rejected: results.every(result => result.status === 'rejected'), count: (await window.desktop.listDrafts()).drafts.length };
  });
  assert.deepEqual(capacity, { rejected: true, count: 10 });
  await page.screenshot({ path: path.join(output, '13-draft-limit.png') });
  await page.locator('.library-card').first().locator('.library-card-open').click();
  assert.equal(await page.getByRole('button', { name: '另存草稿', exact: true }).isDisabled(), true);
  await page.getByRole('button', { name: '返回上一层', exact: true }).click();
  await page.locator('.library-card').first().getByRole('button', { name: /^删除草稿 / }).click();
  await page.getByRole('dialog', { name: '删除这份草稿？' }).getByRole('button', { name: '删除草稿', exact: true }).click();
  await page.getByRole('dialog', { name: '删除这份草稿？' }).waitFor({ state: 'hidden' });
  assert.equal(await page.locator('.library-card').count(), 9);
  assert.equal(await page.getByRole('button', { name: '新建草稿', exact: true }).isEnabled(), true);
  record('Ten-draft limit covers filtered lists, new drafts and save-as; deleting a draft restores availability');

  await page.getByRole('button', { name: '新建草稿', exact: true }).click();
  await selectFiles(Array.from({ length: 10 }, (_, index) => images[index % images.length]));
  await page.locator('.wechat-proof__add').click();
  await page.getByRole('dialog', { name: '添加图片', exact: true }).getByRole('button', { name: '从电脑导入图片', exact: true }).click();
  await page.getByRole('dialog', { name: '添加图片', exact: true }).waitFor({ state: 'hidden' });
  assert.equal(await photos().count(), 9);
  await page.getByRole('button', { name: '编辑模式', exact: true }).click();
  assert.equal(await photos().count(), 10);
  assert.equal(await page.locator('.preview-remove').count(), 10);
  await page.screenshot({ path: path.join(output, '14-edit-all-images.png') });
  await page.getByRole('button', { name: '移除第 10 张图片', exact: true }).click();
  await waitFor(async () => await photos().count() === 9);
  for (let remaining = 8; remaining >= 0; remaining--) {
    await page.getByRole('button', { name: '移除第 1 张图片', exact: true }).click();
    await waitFor(async () => await photos().count() === remaining);
  }
  await page.locator('.wechat-proof__add').waitFor();
  await page.getByRole('button', { name: '完成编辑', exact: true }).click();
  record('WeChat edit mode exposes images beyond nine and safely removes the final image');

  const boundary = await page.evaluate(async () => {
    try { await window.desktop.startJob(crypto.randomUUID(), 'export', { directory: 'C:/', draftId: crypto.randomUUID(), format: 'folder', targets: [] }); return false; }
    catch { return true; }
  });
  assert.equal(boundary, true); assert.deepEqual(errors, []);
  record('Export path boundary and renderer runtime remain sound');
  await writeFile(path.join(output, 'qa-results.json'), JSON.stringify({ passed: true, assertions, rendererErrors: errors, clipboardReadback: clipboardAvailable ? 'passed' : 'unavailable in this Windows test session; failure reporting verified; successful native paste requires interactive-session verification', nativeDeviceTests: 'not performed', cleanVirtualMachine: 'not performed; packaged executable tested with restricted child PATH' }, null, 2));
} catch (error) {
  if (page) { try { await page.screenshot({ path: path.join(work, 'failure.png') }); await writeFile(path.join(work, 'failure-dom.txt'), await page.locator('body').innerText()); } catch {} }
  throw error;
} finally {
  if (application) await application.close().catch(() => {});
  console.log('Test materials retained:', path.relative(root, work));
}
