import { _electron as electron } from 'playwright';
import { mkdtemp, mkdir, readFile, writeFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root = path.resolve(import.meta.dirname, '..');
await mkdir(path.join(root, 'output/test-data'), { recursive: true });
const work = await mkdtemp(path.join(root, 'output/test-data/settings-'));
const destination = path.join(work, '新素材库'), cancelled = path.join(work, '取消迁移目录'), occupied = path.join(work, '已有内容');
for (const directory of [destination, cancelled, occupied]) await mkdir(directory);
await writeFile(path.join(occupied, 'retain.txt'), 'retain');
const env = { ...process.env, SOCIAL_COPY_DATA_DIRECTORY: path.join(work, 'profile') }; delete env.ELECTRON_RUN_AS_NODE;
let app, page; const checks = [];
const pass = text => { console.log('PASS', text); checks.push(text); };
async function launch() {
  app = await electron.launch({ executablePath: path.join(root, 'out/SocialCopyStudio-win32-x64/SocialCopyStudio.exe'), env });
  page = await app.firstWindow(); page.setDefaultTimeout(30000);
  await app.evaluate(({ BrowserWindow }) => { const w = BrowserWindow.getAllWindows()[0]; w.webContents.setBackgroundThrottling(false); w.hide(); });
  await page.getByRole('heading', { name: '我的草稿', exact: true }).waitFor();
}
const choose = files => app.evaluate(({ dialog }, files) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: files }); }, files);
const job = (kind, payload) => page.evaluate(({ kind, payload }) => new Promise((resolve, reject) => {
  const id = crypto.randomUUID(); const off = window.desktop.onJob(info => { if (info.id !== id) return; if (info.status === 'done') { off(); resolve(info.result); } else if (['error', 'cancelled'].includes(info.status)) { off(); reject(Error(info.error)); } });
  window.desktop.startJob(id, kind, payload).catch(error => { off(); reject(error); });
}), { kind, payload });
try {
  await launch();
  const [asset] = await job('images', [path.join(root, 'public/ai-examples/product-before.png')]);
  const draft = await page.evaluate(async asset => { const draft = await window.desktop.createDraft('moments', [asset.id]); return window.desktop.saveDraft({ ...draft, caption: '迁移资料测试 🌊' }); }, asset);
  await page.reload(); await page.locator('.library-card').waitFor();
  const card = await page.locator('.library-card').boundingBox(), button = await page.locator('.draft-delete').boundingBox();
  assert.ok(Math.abs(button.y - card.y - 9) < 2); assert.ok(Math.abs(card.x + card.width - button.x - button.width - 9) < 2);
  await page.screenshot({ path: path.join(work, 'delete-top-right.png') }); pass('Draft delete button is anchored to the card top right');
  await page.locator('.library-card-open').click();
  await page.getByRole('textbox', { name: '发布文案', exact: true }).fill('迁移前最后修改 🌊');
  await page.getByRole('button', { name: '设置', exact: true }).click();
  const settings = page.getByRole('region', { name: '设置', exact: true }); await settings.waitFor();
  const originalInfo = await page.evaluate(() => window.desktop.getInfo());
  assert.equal(await page.evaluate(async target => { try { await window.desktop.changeLibraryDirectory(target); return false; } catch { return true; } }, destination), true);
  await choose([occupied]); await settings.getByRole('button', { name: '选择文件夹', exact: true }).click(); await settings.getByRole('button', { name: '应用新位置', exact: true }).click();
  await settings.getByRole('alert').filter({ hasText: '空文件夹' }).waitFor(); assert.equal((await page.evaluate(() => window.desktop.getInfo())).dataDirectory, originalInfo.dataDirectory);
  assert.equal(await readFile(path.join(occupied, 'retain.txt'), 'utf8'), 'retain');
  pass('Settings reject unapproved and occupied directories without replacing data');
  await app.evaluate((_electron, destination) => {
    const fs = process.getBuiltinModule('node:fs').promises; globalThis.originalOpen = fs.open;
    fs.open = async (...args) => { if (String(args[0]).startsWith(destination)) await new Promise(resolve => setTimeout(resolve, 300)); return globalThis.originalOpen(...args); };
  }, cancelled);
  await choose([cancelled]); await settings.getByRole('button', { name: '选择文件夹', exact: true }).click(); await settings.getByRole('button', { name: '应用新位置', exact: true }).click();
  await settings.getByRole('button', { name: '取消迁移', exact: true }).click(); await settings.getByRole('alert').filter({ hasText: '已取消' }).waitFor();
  await app.evaluate(() => { process.getBuiltinModule('node:fs').promises.open = globalThis.originalOpen; });
  assert.deepEqual(await readdir(cancelled), []); assert.equal((await page.evaluate(() => window.desktop.getInfo())).dataDirectory, originalInfo.dataDirectory);
  pass('Cancel restores the original active directory and removes only incomplete copies');
  await choose([destination]); await settings.getByRole('button', { name: '选择文件夹', exact: true }).click(); await settings.getByRole('button', { name: '应用新位置', exact: true }).click();
  await settings.getByRole('status').filter({ hasText: '已切换到新素材库' }).waitFor();
  assert.equal((await page.evaluate(() => window.desktop.getInfo())).dataDirectory, destination);
  const newDraft = JSON.parse(await readFile(path.join(destination, 'drafts', draft.id + '.json'), 'utf8'));
  assert.equal(newDraft.caption, '迁移前最后修改 🌊');
  const imageBytes = await readFile(path.join(originalInfo.dataDirectory, 'assets', asset.id, 'image.png'));
  assert.deepEqual(await readFile(path.join(destination, 'assets', asset.id, 'image.png')), imageBytes);
  await page.screenshot({ path: path.join(work, 'settings-migrated.png') });
  await settings.getByRole('button', { name: '返回上一层', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.wechat-proof__photo img')?.naturalWidth > 0);
  await page.getByRole('textbox', { name: '发布文案', exact: true }).fill('新目录里的修改');
  await page.getByRole('button', { name: '返回上一层', exact: true }).click();
  await page.getByRole('heading', { name: '我的草稿', exact: true }).waitFor();
  assert.equal(JSON.parse(await readFile(path.join(destination, 'drafts', draft.id + '.json'), 'utf8')).caption, '新目录里的修改');
  assert.equal(JSON.parse(await readFile(path.join(originalInfo.dataDirectory, 'drafts', draft.id + '.json'), 'utf8')).caption, '迁移前最后修改 🌊');
  await app.close(); app = null; await launch();
  assert.equal((await page.evaluate(() => window.desktop.getInfo())).dataDirectory, destination);
  assert.equal((await page.evaluate(() => window.desktop.listDrafts())).drafts[0].caption, '新目录里的修改');
  pass('Migration preserves originals, updates media and saves new edits in the new location after restart');
  await page.getByRole('button', { name: '素材库', exact: true }).click();
  await page.getByRole('button', { name: `查看素材 ${asset.name}`, exact: true }).click();
  await page.getByRole('button', { name: 'AI 图片优化', exact: true }).click();
  const ai = page.getByRole('region', { name: 'AI 图片优化', exact: true }); await ai.waitFor();
  assert.equal(await page.locator('.optimization-steps').count(), 0);
  const templates = ai.getByRole('combobox', { name: '优化模板', exact: true }); assert.equal(await templates.locator('option').count(), 20);
  await templates.selectOption('product'); assert.match(await ai.getByRole('textbox', { name: '优化提示词', exact: true }).inputValue(), /商品/);
  assert.equal(await ai.getByRole('button', { name: '复制原图', exact: true }).isEnabled(), true);
  await page.screenshot({ path: path.join(work, 'compact-ai.png') });
  await choose([path.join(root, 'public/ai-examples/product-after.png')]); await ai.getByRole('button', { name: '导入优化结果', exact: true }).click();
  await ai.getByRole('button', { name: '复制优化图', exact: true }).waitFor();
  const result = (await page.evaluate(() => window.desktop.listLibrary())).assets.find(item => item.optimization);
  assert.equal(result.optimization.sourceId, asset.id); assert.equal(result.optimization.templateId, 'product');
  assert.ok((await readFile(path.join(destination, 'assets', result.id, 'asset.json'))).length);
  pass('Compact AI page selects templates and imports linked results into the configured library');
  await writeFile(path.join(work, 'verification.json'), JSON.stringify({ version: '0.3.13', checks }, null, 2));
} finally { if (app) await app.close(); console.log('Test materials retained:', work); }
